development:
  adapter: postgresql
  encoding: unicode
  database: record_collection_development
  pool: 5
  username: record_collection
  password:

test:
  adapter: postgresql
  database: record_collection_test
  pool: 5
  username: record_collection
  password:
